name: notebook
channels:
  - conda-forge
dependencies:
  - cftime
  - cmaps
  - fsspec=0.7.3
  - intake-esm
  - nc-time-axis
  - netcdf4
  - pangeo-notebook=2020.06.10
  - pip
  - s3fs
  - watermark
  - zarr
  - cartopy
