name: notebook
channels:
  - conda-forge
dependencies:
  - watermark
  - cftime>=1.0.4.2
  - pip:
      - git+https://github.com/hhuangwx/cmaps.git#egg=cmaps
      - git+https://github.com/intake/filesystem_spec.git@master
      - git+https://github.com/dask/s3fs.git@master
      - git+https://github.com/NCAR/intake-esm.git@master
