name: notebook
channels:
  - conda-forge
dependencies:
  - pip
  - watermark
  - cftime==1.0.3.4
  - s3fs>=0.4.0
  - fsspec>=0.6.0
  - pip:
      - git+https://github.com/hhuangwx/cmaps.git#egg=cmaps
      - git+https://github.com/NCAR/intake-esm.git@master
