name: notebook
channels:
  - conda-forge
dependencies:
  - cartopy
  - cftime
  - cmaps
  - dask>=2021.1.0
  - dask-gateway>=0.9.0
  - dask-kubernetes>=0.11.0
  - dask-labextension
  - distributed >=2021.1.0
  - fsspec
  - intake-esm>=2021.1.15
  - ipywidgets
  - jupyter-server-proxy
  - jupyterhub-singleuser
  - jupyterlab>=3
  - nbgitpuller
  - nc-time-axis
  - nodejs
  - panel
  - pip
  - s3fs
  - voila
  - watermark
