name: notebook
channels:
  - conda-forge
dependencies:
  - cartopy
  - cftime
  - cmaps
  - dask
  - dask-labextension
  - distributed
  - fsspec
  - intake-esm>=2021.1.15
  - jupyterlab>=3
  - nbgitpuller
  - nc-time-axis
  - panel
  - pangeo-notebook>=2021.01.16
  - pip
  - s3fs
  - s3fs
  - voila
  - watermark
