name: notebook
channels:
  - conda-forge
dependencies:
  - cartopy
  - cftime
  - cmaps
  - dask
  - dask-labextension
  - distributed
  - fsspec
  - intake-esm>=2021.1.15
  - ipywidgets
  - jupyter-server-proxy
  - jupyterhub-singleuser
  - jupyterlab>=3
  - nbgitpuller
  - nc-time-axis
  - nodejs
  - panel
  - pangeo-dask
  - pip
  - s3fs
  - voila
  - watermark
