name: notebook
channels:
  - conda-forge
dependencies:
  - cftime
  - cmaps
  - fsspec>=0.6.0
  - nc-time-axis
  - pip
  - s3fs>=0.4.0
  - watermark
  - pip:
     - git+https://github.com/NCAR/intake-esm.git@master
