name: notebook
channels:
  - conda-forge
dependencies:
  - cftime
  - cmaps
  - dask-gateway>=0.7.1
  - fsspec>=0.6.0
  - intake-esm
  - nc-time-axis
  - pangeo-notebook=2020.05.04
  - pip
  - s3fs>=0.4.0
  - watermark
