name: notebook
channels:
  - conda-forge
dependencies:
  - cftime
  - cmaps
  - fsspec
  - intake-esm>=2020.8.15
  - nc-time-axis
  - netcdf4
  - pangeo-notebook=2020.08.11
  - pip
  - s3fs
  - watermark
  - zarr
  - cartopy
