name: notebook
channels:
  - conda-forge
dependencies:
  - cftime
  - cmaps
  - dask-gateway>=0.7.1
  - fsspec
  - intake-esm
  - nc-time-axis
  - netcdf4
  - pangeo-notebook=2020.05.04
  - pip
  - s3fs
  - watermark
  - zarr
  - cartopy
