name: Update catalog

on:
  push:
    branches:
      - master
    paths:
      - "intake-catalogs/*"

  pull_request:
    branches:
      - master
    paths:
      - "intake-catalogs/*"

  workflow_dispatch: # allows you to trigger manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install fsspec xarray cftime dask[complete] zarr s3fs tqdm

      - name: Update catalog
        run: |
          python intake-catalogs/catalog-builder.py
          git status

      - name: Upload to S3
        # if: github.ref == 'refs/heads/master'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exclude "*" --include "aws-cesm1-le*"  --dryrun
        env:
          AWS_S3_BUCKET: s3://ncar-cesm-lens/catalogs/
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          SOURCE_DIR: intake-catalogs
