name: linting

on:
  push:
  pull_request:

jobs:
  linting:
    if: github.repository == 'NCAR/cesm-lens-aws'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint notebooks 
        - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
          with:
            disable-checks: outputs,execution_count
