name: linting

on:
  push:
  pull_request:

jobs:
  linting:
    if: github.repository == 'NCAR/cesm-lens-aws'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files
